[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NETLIFY_NEXTJS_SKIP_PREPARE = "true"
  NETLIFY_SKIP_NEXTJS_PLUGIN = "true"
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
